# Wasd
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: خانه
email: mostafamoradi2012@yahoo.com
description: دانشجوی سال سوم کامپیوتر گرایش نرم افزار هستم می خوام مطالبی که جمع آوری می کنم رو اینجا بزارم.  # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mostafamoradi2
github_username:  martional

# Build settings
markdown: kramdown
